
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Dec 23 02:24:54 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BOOLSTOP = 44;
  public static final int CONST = 10;
  public static final int BOOLGTOP = 42;
  public static final int NUMCONST = 14;
  public static final int PLUSOP = 36;
  public static final int BOOLGTEOP = 43;
  public static final int MINUSOP = 33;
  public static final int LBROP = 7;
  public static final int CONTINUE = 25;
  public static final int NEWOP = 35;
  public static final int COMMAOP = 12;
  public static final int DECOP = 30;
  public static final int CLASS = 17;
  public static final int STAROP = 37;
  public static final int IF = 20;
  public static final int BOOLANDOP = 32;
  public static final int LSBROP = 5;
  public static final int SEMIOP = 11;
  public static final int EOF = 0;
  public static final int RETURN = 26;
  public static final int RBROP = 8;
  public static final int error = 1;
  public static final int RSBROP = 6;
  public static final int BREAK = 24;
  public static final int IDENT = 9;
  public static final int VOID = 19;
  public static final int BOOLEQUOP = 40;
  public static final int ASNOP = 13;
  public static final int BOOLOROP = 31;
  public static final int INCOP = 29;
  public static final int LVBROP = 3;
  public static final int POINTOP = 34;
  public static final int ELSE = 21;
  public static final int READ = 27;
  public static final int CHARCONST = 16;
  public static final int RVBROP = 4;
  public static final int WHILE = 23;
  public static final int DIVOP = 38;
  public static final int BOOLCONST = 15;
  public static final int EXTENDS = 18;
  public static final int PROG = 2;
  public static final int MODOP = 39;
  public static final int BOOLSTEOP = 45;
  public static final int BOOLNEQUOP = 41;
  public static final int PRINT = 28;
  public static final int DO = 22;
}

